#!/usr/bin/env bash
# ARG_OPTIONAL_SINGLE([gnulib-source],[g],[gnulib source tree to take gnulib-tool from; if omitted, GNULIB_SRCDIR or a fresh clone],[])
# ARG_OPTIONAL_BOOLEAN([refresh],[],[re-import the snapshot's current modules (no modules allowed)])
# ARG_OPTIONAL_BOOLEAN([remove],[],[remove the given modules from the snapshot])
# ARG_OPTIONAL_BOOLEAN([keep-temp],[k],[do not delete the temporary directory (package, build and logs) at the end])
# ARG_POSITIONAL_INF([module],[gnulib modules to add (or to remove with --remove)],[0])
# ARG_POSITIONAL_DOUBLEDASH([])
# ARG_OPTION_STACKING([none])
# ARG_RESTRICT_VALUES([no-any-options])
# DEFINE_SCRIPT_DIR([])
# ARG_HELP([Regenerate third_party/gnulib, the gnulib snapshot the CMake build uses.],[The module list is the snapshot's current list (gnulib-snapshot.cmake) plus the\ngiven modules, or minus them with --remove, or unchanged with --refresh.\ngnulib-tool --create-testdir generates a throwaway Autotools package for that\nlist in a temporary directory, which is configured for C only and built.\nconfig.h (without the package identity), the generated headers, the compiled\ngnulib sources and gnulib-snapshot.cmake then replace the snapshot directory.\nExamples:\n  tools/update-gnulib-snapshot.sh getline pread pwrite\n  tools/update-gnulib-snapshot.sh vfprintf-posix\n  tools/update-gnulib-snapshot.sh --remove vfprintf-posix\n  tools/update-gnulib-snapshot.sh --refresh])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.11.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.dev for more info


die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}


evaluate_strictness()
{
	! [[ "$2" =~ ^--?[a-zA-Z] ]] || die "You have passed '$2' as a value of argument '$1'. It looks like that you are trying to pass an option instead of the actual value, which is considered a fatal error."
}


# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
_arg_module=()
# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_gnulib_source=
_arg_refresh="off"
_arg_remove="off"
_arg_keep_temp="off"


print_help()
{
	printf '%s\n' "Regenerate third_party/gnulib, the gnulib snapshot the CMake build uses."
	printf 'Usage: %s [-g|--gnulib-source <arg>] [--(no-)refresh] [--(no-)remove] [-k|--(no-)keep-temp] [-h|--help] [--] [<module-1>] ... [<module-n>] ...\n' "$(basename "$0")"
	printf '\t%s\n' "<module>: gnulib modules to add (or to remove with --remove)"
	printf '\t%s\n' "-g, --gnulib-source: gnulib source tree to take gnulib-tool from; if omitted, GNULIB_SRCDIR or a fresh clone (no default)"
	printf '\t%s\n' "--refresh, --no-refresh: re-import the snapshot's current modules (no modules allowed) (off by default)"
	printf '\t%s\n' "--remove, --no-remove: remove the given modules from the snapshot (off by default)"
	printf '\t%s\n' "-k, --keep-temp, --no-keep-temp: do not delete the temporary directory (package, build and logs) at the end (off by default)"
	printf '\t%s\n' "-h, --help: Prints help"
	echo
	echo 'Short options stacking mode is not supported.'
	printf '\n%s\n' "The module list is the snapshot's current list (gnulib-snapshot.cmake) plus the
given modules, or minus them with --remove, or unchanged with --refresh.
gnulib-tool --create-testdir generates a throwaway Autotools package for that
list in a temporary directory, which is configured for C only and built.
config.h (without the package identity), the generated headers, the compiled
gnulib sources and gnulib-snapshot.cmake then replace the snapshot directory.
Examples:
  tools/update-gnulib-snapshot.sh getline pread pwrite
  tools/update-gnulib-snapshot.sh vfprintf-posix
  tools/update-gnulib-snapshot.sh --remove vfprintf-posix
  tools/update-gnulib-snapshot.sh --refresh"
}


parse_commandline()
{
	_positionals_count=0
	local _key
	while test $# -gt 0
	do
		_key="$1"
		if test "$_key" = '--'
		then
			shift
			test $# -gt 0 || break
			_positionals+=("$@")
			_positionals_count=$((_positionals_count + $#))
			shift $(($# - 1))
			_last_positional="$1"
			break
		fi
		case "$_key" in
			-g|--gnulib-source)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_gnulib_source="$2"
				shift
				evaluate_strictness "$_key" "$_arg_gnulib_source"
				;;
			--gnulib-source=*)
				_arg_gnulib_source="${_key##--gnulib-source=}"
				evaluate_strictness "$_key" "$_arg_gnulib_source"
				;;
			--no-refresh|--refresh)
				_arg_refresh="on"
				test "${1:0:5}" = "--no-" && _arg_refresh="off"
				;;
			--no-remove|--remove)
				_arg_remove="on"
				test "${1:0:5}" = "--no-" && _arg_remove="off"
				;;
			-k|--no-keep-temp|--keep-temp)
				_arg_keep_temp="on"
				test "${1:0:5}" = "--no-" && _arg_keep_temp="off"
				;;
			-h|--help)
				print_help
				exit 0
				;;
			*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


assign_positional_args()
{
	local _positional_name _shift_for=$1
	_positional_names=""
	_our_args=$((${#_positionals[@]} - 0))
	for ((ii = 0; ii < _our_args; ii++))
	do
		_positional_names="$_positional_names _arg_module[$((ii + 0))]"
	done

	shift "$_shift_for"
	for _positional_name in ${_positional_names}
	do
		test $# -gt 0 || break
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
		evaluate_strictness "$_positional_name" "${1##_arg}"
		shift
	done
}

parse_commandline "$@"
assign_positional_args 1 "${_positionals[@]}"

# OTHER STUFF GENERATED BY Argbash
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || { echo "Couldn't determine the script's running directory, which probably matters, bailing out" >&2; exit 2; }

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash
#
# Regenerate third_party/gnulib (the gnulib snapshot the CMake build uses).
#

set -euo pipefail

# ---------------------------------------------------------------- settings
GNULIB_REF=                   # gnulib commit or tag for a fresh clone (empty: latest)
OUTPUT=third_party/gnulib     # snapshot directory, relative to the repository root
# gnulib-tool runs its Python implementation when python3 >= 3.7 is found. MSYS2's
# native python3 cannot run shell-script tools such as libtoolize (WinError 2),
# so use the shell implementation.
export GNULIB_TOOL_IMPL=sh
GNULIB_URL=https://github.com/coreutils/gnulib.git   # GitHub mirror of gnulib

console_log() { printf '== %s\n' "$*"; }
console_errexit() {
	printf 'error: %s failed. Its log (%s):\n' "$*" "$log/$1.log" >&2
	cat "$log/$1.log" >&2
	die "error: $* failed (log above; --keep-temp keeps the temporary directory, e.g. for config.log)"
}
# sort and comm in byte order, whatever the user's locale (comm needs sort's order).
sort() { LC_ALL=C command sort "$@"; }
comm() { LC_ALL=C command comm "$@"; }

# ---------------------------------------------------------------- preflight
repo=$(cd "$script_dir/.." && pwd)    # the script lives in tools/, one level below the repository root
modules=("${_arg_module[@]}")
case $OUTPUT in /*|[A-Za-z]:*) output=$OUTPUT ;; *) output=$repo/$OUTPUT ;; esac

for tool in git autoreconf automake libtoolize make; do
	command -v "$tool" >/dev/null || die "error: '$tool' not found (MSYS2: pacman -S --needed base-devel autotools git)"
done

# Refuse to wipe a directory that is not a snapshot.
if [ -d "$output" ] && [ -n "$(ls -A "$output")" ] && [ ! -f "$output/gnulib-snapshot.cmake" ]; then
	die "error: $output exists and is not a gnulib snapshot (no gnulib-snapshot.cmake); refusing to replace it"
fi

# The snapshot's current module list.
current=()
if [ -f "$output/gnulib-snapshot.cmake" ]; then
	read -r -a current <<< "$(sed -n 's/^set (GNULIB_SNAPSHOT_MODULES \(.*\))$/\1/p' "$output/gnulib-snapshot.cmake")"
fi
sorted() { [ $# -eq 0 ] || printf '%s\n' "$@" | sort -u; }

if [ "$_arg_refresh" = on ] && [ "$_arg_remove" = on ]; then
	die "error: --refresh and --remove cannot be combined"
elif [ "$_arg_refresh" = on ]; then
	[ ${#modules[@]} -eq 0 ] || die "error: --refresh takes no modules; it re-imports the current list"
	[ ${#current[@]} -gt 0 ] || die "error: --refresh needs an existing snapshot in $output"
	mapfile -t wanted < <(sorted "${current[@]}")
	action="refresh"
elif [ "$_arg_remove" = on ]; then
	[ ${#modules[@]} -gt 0 ] || die "error: --remove needs the modules to remove"
	[ ${#current[@]} -gt 0 ] || die "error: --remove needs an existing snapshot in $output"
	missing=$(comm -13 <(sorted "${current[@]}") <(sorted "${modules[@]}") | tr '\n' ' ')
	[ -z "$missing" ] || die "error: not in the snapshot: $missing(current: ${current[*]})"
	mapfile -t wanted < <(comm -23 <(sorted "${current[@]}") <(sorted "${modules[@]}"))
	[ ${#wanted[@]} -gt 0 ] || die "error: that would remove every module; delete $output instead"
	action="remove ${modules[*]}"
else
	[ ${#modules[@]} -gt 0 ] || die "error: give the modules to add, or use --refresh / --remove"
	mapfile -t wanted < <(sorted "${current[@]}" "${modules[@]}")
	action="add ${modules[*]}"
fi
console_log "$action: ${current[*]:-(no snapshot)} -> ${wanted[*]}"

work=$(mktemp -d "${TMPDIR:-/tmp}/gnulib-snapshot.XXXXXX")
cleanup() {
	if [ "$_arg_keep_temp" = on ]; then echo "temporary directory kept: $work"; else rm -rf "$work"; fi
}
trap cleanup EXIT
pkg=$work/package
log=$work/log
mkdir -p "$log"

# ---------------------------------------------------------------- 1. get gnulib
gnulib=${_arg_gnulib_source:-${GNULIB_SRCDIR:-}}
if [ -z "$gnulib" ]; then
	gnulib=$work/gnulib
	console_log "clone gnulib ${GNULIB_REF:-(latest)}"
	git clone -q --depth 1 "$GNULIB_URL" "$gnulib"
	if [ -n "$GNULIB_REF" ]; then
		git -C "$gnulib" fetch -q --depth 1 origin "$GNULIB_REF"
		git -C "$gnulib" checkout -q --detach FETCH_HEAD
	fi
fi
[ -x "$gnulib/gnulib-tool" ] || die "error: no gnulib-tool in $gnulib"
gnulib_version=$(git -C "$gnulib" rev-parse HEAD 2>/dev/null || echo "unknown (not a git checkout: $gnulib)")
# gnulib-tool only warns about unknown modules, so check against its own module list.
gnulib_modules=$("$gnulib/gnulib-tool" --list) || die "error: gnulib-tool --list failed"
wanted_unknown=()
for m in "${wanted[@]}"; do grep -q -x -F -- "$m" <<< "$gnulib_modules" || wanted_unknown+=("$m"); done
if [ ${#wanted_unknown[@]} -gt 0 ]; then
	die "error: no such gnulib module: ${wanted_unknown[*]} (gnulib ${gnulib_version:0:12})"
fi

# ---------------------------------------------------------------- 2. create the throwaway package
console_log "gnulib-tool --create-testdir ${wanted[*]}"
"$gnulib/gnulib-tool" \
	--create-testdir \
	--dir="$pkg" \
	--without-tests \
	--libtool \
	--single-configure \
	"${wanted[@]}" \
	> "$log/gnulib-tool.log" 2>&1 ||
	console_errexit gnulib-tool --create-testdir "${wanted[@]}"

# ---------------------------------------------------------------- 3. build the package
# The snapshot is for C only: with CXX=no, libtool leaves its C++ tag empty and
# gnulib skips its C++ checks (the testdir asks for C++ with LT_LANG([C++])).
console_log "configure CXX=no"
(
	cd "$pkg" &&
	./configure \
		CXX=no
) > "$log/configure.log" 2>&1 ||
	console_errexit configure CXX=no
console_log "make -C gllib"
make \
	-C "$pkg/gllib" \
	-j"$(nproc 2>/dev/null || echo 2)" \
	> "$log/make.log" 2>&1 ||
	console_errexit make -C gllib

# ---------------------------------------------------------------- 4. list sources and generated files
makevar() {
	printf 'print-%%: ; @echo $($*)\n' | make -s -C "$pkg/gllib" -f Makefile -f - "print-$1"
}
# Object names carry libtool's per-target prefix after any subdirectory
# (unicase/libgnu_la-tolower.lo), or none at all (unicase/tolower.lo).
sources=()
objects=()
for obj in $(makevar am_libgnu_la_OBJECTS) $(makevar libgnu_la_LIBADD); do
	case $obj in *.lo) objects+=("$obj"); obj=${obj/libgnu_la-/}; sources+=("${obj%.lo}.c") ;; esac
done
generated=(config.h $(makevar BUILT_SOURCES))
[ ${#sources[@]} -gt 0 ] || die "error: no gnulib sources were compiled"

host=$(makevar host)
cc=$(makevar CC)
cc_name=$(basename "${cc%% *}")
cppflags=$(makevar CPPFLAGS)
compiler="$($cc -dumpfullversion 2>/dev/null || $cc -dumpversion)"
crt=$(printf '#include <stdio.h>\n#ifdef _UCRT\nucrt\n#else\nmsvcrt\n#endif\n' | $cc $cppflags -E -P - 2>/dev/null | tail -1)

# ---------------------------------------------------------------- 5. find the helper headers
# Every file the compiler read: make's dependency files plus gcc -M on each generated
# header (-M, since -MM drops headers reached through system headers), read by make.
console_log "$cc_name -M (generated headers)"
for header in "${generated[@]}"; do
	if [[ $header == *.h && $header != config.h ]]; then
		(
			cd "$pkg/gllib" &&
			$cc $cppflags \
				-M \
				-MT __snapshot_deps__ \
				-I. \
				-include ../config.h \
				-x c \
				"$header"
		) >> "$work/generated.d" 2>> "$log/$cc_name.log" ||
		console_errexit "$cc_name" -M "$header"
	fi
done
cat > "$work/read.mk" <<'EOF'
include $(shell find . -path '*/.deps/*.P*o')
-include $(GENERATED_D)
read = $(sort $(wildcard $(patsubst $(CURDIR)/%,%,$(filter $(CURDIR)/%,$(abspath $^)))))
%.lo: ; $(foreach f,$(read),$(info $(f)))
__snapshot_deps__: ; $(foreach f,$(read),$(info $(f)))
EOF
make -r -R -B -s \
	-C "$pkg/gllib" \
	-f "$work/read.mk" \
	GENERATED_D="$work/generated.d" \
	"${objects[@]}" __snapshot_deps__ \
	> "$work/read.txt"
sort -u -o "$work/read.txt" "$work/read.txt"
printf '%s\n' "${sources[@]}" | sort > "$work/sources.txt"
printf '%s\n' "${generated[@]}" | sort > "$work/generated.txt"
# What is read but neither compiled nor generated: helper headers (and any
# non-header file a source includes).
mapfile -t headers < <(
	comm -23 "$work/read.txt" "$work/sources.txt" |
	comm -23 - "$work/generated.txt"
)

# ---------------------------------------------------------------- 6. assemble the snapshot
out=$work/out
mkdir -p "$out"
# config.h is force-included after the command-line -D options, so its package
# identity would override the CMake build's (e.g. VERSION); leave it out.
sed -E '/^#define (PACKAGE|PACKAGE_[A-Z]+|VERSION) /d' "$pkg/config.h" > "$out/config.h"
for f in "${sources[@]}" "${generated[@]}" "${headers[@]}"; do
	[ "$f" = config.h ] && continue
	[ -f "$pkg/gllib/$f" ] || die "error: $f is missing from gllib"
	mkdir -p "$out/$(dirname "$f")"
	cp "$pkg/gllib/$f" "$out/$f"
done

cat > "$out/gnulib-snapshot.cmake" <<EOF
# Generated by tools/update-gnulib-snapshot.sh. Do not edit.
#
# Read by src/CMakeLists.txt, which requires GNULIB_SNAPSHOT_SOURCES.
# The other variables record how the snapshot was made.

# gllib/Makefile: am_libgnu_la_OBJECTS then libgnu_la_LIBADD (libtool archive order)
set (GNULIB_SNAPSHOT_SOURCES ${sources[*]})

# gllib/Makefile: BUILT_SOURCES, plus config.h from configure (package identity removed)
set (GNULIB_SNAPSHOT_GENERATED ${generated[*]})

# Other files the compiler read through #include (dependency output): helper headers
set (GNULIB_SNAPSHOT_HEADERS ${headers[*]})

set (GNULIB_SNAPSHOT_MODULES ${wanted[*]})
set (GNULIB_SNAPSHOT_LANGUAGES "C")   # configured with CXX=no: regenerate if C++ code includes these headers
set (GNULIB_SNAPSHOT_GNULIB "${gnulib_version}")
set (GNULIB_SNAPSHOT_HOST "${host}")
set (GNULIB_SNAPSHOT_CRT "${crt}")
set (GNULIB_SNAPSHOT_COMPILER "${compiler}")
EOF

# ---------------------------------------------------------------- 7. replace the snapshot
rm -rf "$output"
mkdir -p "$(dirname "$output")"
cp -r "$out" "$output"

console_log "done: $output"
printf 'modules:\t%s\n' "${wanted[*]}"
printf 'files:\t\t%s sources, %s generated, %s headers\n' "${#sources[@]}" "${#generated[@]}" "${#headers[@]}"
printf 'built on:\t%s, %s, %s\n' "$host" "$crt" "$compiler"

# ] <-- needed because of Argbash
